version: "3.8"
services:
    api:
        container_name: api
        restart: always
        build: .
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        volumes:
            - .:/usr/src/app
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:${DB_PORT}"
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - data:/data/db
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - "5050:${PGADMIN_PORT}"
volumes:
    data:
